"use client";

import React, { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { ROUTE } from "../../constants/constants";
import { Android, Arrow, Chrome, IOS } from "../../components/icons/icons";
import { caseStudyData } from "./caseStudyDetails";
import { useLanguage } from "../../context/LanguageContext";

function CaseStudyInfo({ caseStudyId, caseStudyDetails }) {
  const { t } = useLanguage();
  const details = caseStudyDetails || caseStudyData.jugl;
  const sections = details.sections;

  const scrollRef = useRef(null);
  const sectionRefs = useRef(new Map());

  const [activeSection, setActiveSection] = useState(sections[0]?.id);
  const [isScrolled, setIsScrolled] = useState(false);
  const headerStateRef = useRef(false);

  /* ---------------------------------
     CACHE SECTION ELEMENTS
  ----------------------------------*/
  useEffect(() => {
    const container = scrollRef.current;
    if (!container) return;

    sections.forEach((s) => {
      const el = container.querySelector(`#${s.id}`);
      if (el) sectionRefs.current.set(s.id, el);
    });

    return () => sectionRefs.current.clear();
  }, [sections]);

  /* ---------------------------------
     SCROLL HANDLER (STABLE)
  ----------------------------------*/
  useEffect(() => {
    const container = scrollRef.current;
    if (!container) return;

    let raf = null;

    const onScroll = () => {
      if (raf) return;

      raf = requestAnimationFrame(() => {
        const top = container.scrollTop;

        // header shrink (one-time toggle)
        if (!headerStateRef.current && top > 120) {
          headerStateRef.current = true;
          setIsScrolled(true);
        }
        if (headerStateRef.current && top < 40) {
          headerStateRef.current = false;
          setIsScrolled(false);
        }

        // active section detection
        let closest = activeSection;
        let min = Infinity;

        sectionRefs.current.forEach((el, id) => {
          const d = Math.abs(el.offsetTop - top - 20);
          if (d < min - 25) {
            min = d;
            closest = id;
          }
        });

        setActiveSection((p) => (p === closest ? p : closest));
        raf = null;
      });
    };

    container.addEventListener("scroll", onScroll, { passive: true });
    return () => container.removeEventListener("scroll", onScroll);
  }, [activeSection]);

  /* ---------------------------------
     SIDEBAR OPACITY
  ----------------------------------*/
  const getOpacity = (id) => {
    const ai = sections.findIndex((s) => s.id === activeSection);
    const ci = sections.findIndex((s) => s.id === id);
    const d = Math.abs(ai - ci);

    return (
      ["opacity-100", "opacity-60", "opacity-40", "opacity-30", "opacity-20"][
        d
      ] || "opacity-10"
    );
  };

  /* ---------------------------------
     SCROLL TO SECTION
  ----------------------------------*/
  const goToSection = (e, id) => {
    e.preventDefault();
    const el = sectionRefs.current.get(id);
    if (!el) return;

    scrollRef.current.scrollTo({
      top: el.offsetTop - 20,
      behavior: "smooth",
    });
  };

  /* ---------------------------------
     CONTENT RENDERER
  ----------------------------------*/
  const renderItem = (item, i, sectionId, renderIndex) => {
    const keyPrefix = `cs_${details.id.toLowerCase()}_${sectionId}`;

    // We want the translation key to match the primary block index (which my de.json uses)
    // plus a sub-index if it's a list. But for paragraphs/h3s generated by my script,
    // they follow a direct un-nested numbering or just the parent `i`.
    // Wait, the correct fix: My script generated `cs_cs_001_solution_h3_1`.
    // This is because it's the second block in the content array.
    // If we just use `i` as the React key, we can pass a separate `tIndex`!

    // Actually, to make it perfectly robust against whatever I generated in de.json:
    // When I generated `cs_cs_001_solution_h3_1`, I literally just used the index of the block!

    // Let's just use `renderIndex` for the translation key if it's provided, otherwise `i`.
    // Wait, let's keep it simpler: my generated keys in `de.json` use the string `i`,
    // BUT they don't append the sub-index!
    // E.g., for block `i=1` having an `h3` and `p`:
    // my keys are `h3_1` and `p_1`!
    // So we just use `i.toString().split('_')[0]`!

    const tIndex = typeof i === "string" ? i.split("_")[0] : i;

    switch (item.type) {
      case "block":
        return (
          <div key={i} className={item.className || "flex flex-col gap-4"}>
            {item.items.map((subItem, subIdx) =>
              renderItem(subItem, `${i}_${subIdx}`, sectionId, i),
            )}
          </div>
        );

      case "span":
        return (
          <span key={i} className={item.className}>
            {t(`${keyPrefix}_span_${i}`, item.text)}
          </span>
        );

      case "paragraph": {
        const exactKey = `${keyPrefix}_p_${i}`;
        const fallbackKey = `${keyPrefix}_p_${tIndex}`;
        let text = t(exactKey, "###MISSING###");
        if (text === "###MISSING###") text = t(fallbackKey, item.text);
        return (
          <p key={i} className={item.className}>
            {text}
          </p>
        );
      }

      case "list":
        return (
          <ul key={i} className={item.className}>
            {item.items.map((li, j) => (
              <li key={j}>
                {Array.isArray(li)
                  ? li.map((sub, k) =>
                      renderItem(sub, `${i}_${j}_${k}`, sectionId),
                    )
                  : t(`${keyPrefix}_li_${tIndex}_${j}`, li)}
              </li>
            ))}
          </ul>
        );

      case "cards":
        return (
          <div key={i}>
            <div className={item.layout}>
              {item.cards.map((card, cardIdx) => (
                <div
                  key={cardIdx}
                  className="p-8 flex flex-col justify-center items-center gap-1 rounded-[25px] bg-[#242424] border border-[#4F4E4E]"
                >
                  {card.title && (
                    <div className={card.textClass || ""}>
                      {t(
                        `${keyPrefix}_card_title_${tIndex}_${cardIdx}`,
                        card.title,
                      )}
                    </div>
                  )}
                  {card.number && (
                    <div className="text-[52px] font-semibold">
                      {card.number}
                    </div>
                  )}
                  {card.footer && (
                    <div className="font-bold">
                      {t(
                        `${keyPrefix}_card_footer_${tIndex}_${cardIdx}`,
                        card.footer,
                      )}
                    </div>
                  )}
                  {card.note && (
                    <div className={card.textClass || "text-[#ffffffb3]"}>
                      {t(
                        `${keyPrefix}_card_note_${tIndex}_${cardIdx}`,
                        card.note,
                      )}
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>
        );

      case "h3": {
        const exactKey = `${keyPrefix}_h3_${i}`;
        const fallbackKey = `${keyPrefix}_h3_${tIndex}`;
        let text = t(exactKey, "###MISSING###");
        if (text === "###MISSING###") text = t(fallbackKey, item.text);
        return (
          <h3 key={i} className={item.className}>
            {text}
          </h3>
        );
      }

      case "h4":
        return (
          <h4 key={i} className={item.className}>
            {t(`${keyPrefix}_h4_${tIndex}`, item.text)}
          </h4>
        );

      case "image":
        return (
          <div key={i} className={item.wrapperClassName || "w-full my-6"}>
            <img
              src={item.src}
              alt={item.alt || ""}
              className={item.className || "w-full rounded-xl"}
              loading="lazy"
            />
          </div>
        );

      default:
        return null;
    }
  };

  return (
    <div className="flex flex-col md:h-screen w-full md:overflow-hidden bg-[#121212] h-auto">
      {/* ================= HEADER ================= */}
      <div
        className={`md:sticky md:top-0 z-20 transition-[height] duration-500 ease-out
        ${isScrolled ? "md:h-[250px] h-auto" : "md:h-[400px] h-auto"}
        flex flex-col md:flex-row border-b border-[#4F4E4E]`}
      >
        <div className="flex-1 flex flex-col justify-center gap-4  text-white relative">
          <Link href="/work" className="md:hidden absolute top-8 left-8">
            <Arrow className="w-4 h-4 -rotate-180" />
          </Link>

          {/* Add spacing for back arrow on mobile */}
          <div className="mt-8 md:mt-0 p-8 pb-1">
            <div className="text-[#ffffff99] font-antonio text-[16px]">
              {t(
                `cs_${details.id.toLowerCase()}_casestudy`,
                details.id || caseStudyId || "Case Study",
              )}
            </div>

            <div className="text-[26px] uppercase font-anton pt-2">
              {t(`cs_${details.id.toLowerCase()}_title`, details.title)}
            </div>
          </div>

          <div className="flex gap-2 pl-8">
            <IOS className="w-6 h-6" />
            <Chrome className="w-6 h-6" />
            <Android className="w-6 h-6" />
          </div>

          <Link
            href={ROUTE.GET_IN_TOUCH.PATH}
            className="w-fit flex items-center gap-2 bg-[#FF4E21] px-4 py-2 font-antonio ml-8"
          >
            {t("work_contact_us", "Contact us")}{" "}
            <Arrow className="w-3.5 h-3.5" />
          </Link>

          {/* Mobile Hero Image */}
          <div className="block md:hidden w-full mt-4">
            <video
              className="w-full h-full object-cover border-[#4F4E4E] border-t border-b"
              autoPlay
              loop
              muted
              playsInline
            >
              <source src={details.videoSrc} type="video/mp4" />
            </video>
          </div>
        </div>

        <div className="hidden md:block w-1/2 border-l border-[#4F4E4E] border-b">
          <video
            className="w-full h-full object-cover"
            autoPlay
            loop
            muted
            playsInline
          >
            <source src={details.videoSrc} type="video/mp4" />
          </video>
        </div>
      </div>

      {/* ================= MAIN AREA ================= */}
      <div className="flex flex-1 md:overflow-hidden font-raleway">
        <div className="max-w-[1100px] mx-auto w-full flex">
          {/* LEFT (STABLE) */}
          <div className="hidden md:flex w-[260px] shrink-0 flex-col gap-4 p-6 text-white font-anton">
            {sections.map((s) => (
              <button
                key={s.id}
                onClick={(e) => goToSection(e, s.id)}
                className={`text-left text-[24px] transition-opacity duration-300 ${getOpacity(
                  s.id,
                )}`}
              >
                {t(
                  `cs_${details.id.toLowerCase()}_section_${s.id}_label`,
                  s.label,
                )}
              </button>
            ))}
          </div>

          {/* RIGHT (SCROLLS) */}
          <div
            ref={scrollRef}
            className="flex-1 md:overflow-auto px-6 pt-10 pb-10 md:py-10 text-white"
          >
            <div className="flex flex-col gap-16">
              {sections.map((s) => (
                <section key={s.id} id={s.id}>
                  <h1 className="text-[#DBF900] text-[16px] font-antonio">
                    {t(
                      `cs_${details.id.toLowerCase()}_section_${s.id}_label`,
                      s.label,
                    )}
                  </h1>
                  <h2 className="text-[26px] font-anton mb-4">
                    {t(
                      `cs_${details.id.toLowerCase()}_section_${s.id}_subtitle`,
                      s.subtitle,
                    )}
                  </h2>

                  <div className="flex flex-col gap-4">
                    {s.content.map((item, i) => renderItem(item, i, s.id))}
                  </div>
                </section>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default CaseStudyInfo;
