/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 brobot.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/3dmodels/brobot/brobot.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.material} position={[2.005, -0.524, -0.327]} rotation={[0, -0.725, 0]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.material} position={[2.005, -0.524, -0.377]} rotation={[0, -0.725, 0]} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.material} position={[2.433, -0.74, 0.289]} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.material} position={[2.62, -0.299, 0.285]} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.material_1} position={[2.628, -0.557, 0.288]} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.material_1} position={[2.353, -1.448, 0.717]} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.material} position={[2.082, -0.524, -0.983]} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.material} position={[2.242, -0.524, 0.274]} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.material} position={[1.814, -0.162, 0.607]} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.tors} position={[1.814, -0.082, 1.552]} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.material} position={[1.814, -0.6, 0.189]} />
      <mesh geometry={nodes.Object_26.geometry} material={materials.material} position={[2.531, -0.533, 2.763]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_28.geometry} material={materials.material} position={[2.438, -0.592, 2.763]} rotation={[Math.PI / 2, -Math.PI / 3, 0]} />
      <mesh geometry={nodes.Object_30.geometry} material={materials.material} position={[2.34, -0.54, 2.763]} rotation={[-Math.PI / 2, -Math.PI / 3, -Math.PI]} />
      <mesh geometry={nodes.Object_32.geometry} material={materials.material} position={[2.336, -0.43, 2.763]} rotation={[-Math.PI / 2, 0, Math.PI]} />
      <mesh geometry={nodes.Object_34.geometry} material={materials.material} position={[2.429, -0.371, 2.763]} rotation={[-Math.PI / 2, Math.PI / 3, Math.PI]} />
      <mesh geometry={nodes.Object_36.geometry} material={materials.material} position={[2.527, -0.423, 2.763]} rotation={[Math.PI / 2, Math.PI / 3, 0]} />
      <mesh geometry={nodes.Object_38.geometry} material={materials.material} position={[2.433, -0.481, 2.753]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_40.geometry} material={materials.material} position={[2.433, -0.481, 2.577]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_42.geometry} material={materials.material} position={[2.433, -0.481, 1.076]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_44.geometry} material={materials.material} position={[2.433, -0.481, 2.854]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_46.geometry} material={materials.material} position={[1.814, -0.524, 2.366]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_48.geometry} material={materials.material} position={[2.643, -0.469, -0.303]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_50.geometry} material={materials.material} position={[2.433, -0.479, 0.256]} />
      <mesh geometry={nodes.Object_52.geometry} material={materials.material} position={[2.433, -1.213, 0.284]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_54.geometry} material={materials.material} position={[1.567, 0.804, 0.545]} />
      <mesh geometry={nodes.Object_56.geometry} material={materials.material} position={[1.567, 0.279, 0.647]} />
      <mesh geometry={nodes.Object_58.geometry} material={materials.material} position={[2.028, 0.761, 0.985]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_60.geometry} material={materials.material} position={[1.676, 0.449, 0.83]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_62.geometry} material={materials.material} position={[1.37, 0.668, -0.034]} rotation={[-2.888, 0, 0]} />
      <mesh geometry={nodes.Object_64.geometry} material={materials.material} position={[1.769, 1.171, -1.255]} rotation={[-1.362, 0, 0]} />
      <mesh geometry={nodes.Object_66.geometry} material={materials.material} position={[1.567, 0.888, -0.972]} rotation={[0.233, 0, 0]} />
      <mesh geometry={nodes.Object_68.geometry} material={materials.material} position={[1.576, 0.341, 0.114]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_70.geometry} material={materials.tors} position={[-0.009, 0.063, -0.839]} rotation={[-0.159, 0, 0]} />
      <mesh geometry={nodes.Object_72.geometry} material={materials.tors} position={[-0.262, -1.337, 1.38]} />
      <mesh geometry={nodes.Object_74.geometry} material={materials.tors} position={[0.17, 0, -1.086]} />
      <mesh geometry={nodes.Object_76.geometry} material={materials.tors} position={[0, -0.266, -1.203]} />
      <mesh geometry={nodes.Object_78.geometry} material={materials.tors} position={[0, 0.693, -0.33]} rotation={[0.614, 0, 0]} />
      <mesh geometry={nodes.Object_80.geometry} material={materials.tors} position={[0, -0.922, 0.916]} />
      <mesh geometry={nodes.Object_82.geometry} material={materials.tors} position={[0, 0.48, 0.178]} />
      <mesh geometry={nodes.Object_84.geometry} material={materials.tors} position={[0, -0.174, 0.807]} rotation={[0.414, 0, 0]} />
      <mesh geometry={nodes.Object_86.geometry} material={materials.material_1} position={[1.444, 0.15, -0.161]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_88.geometry} material={materials.tors} position={[1.204, -0.201, 0.817]} rotation={[-0.025, -0.276, -1.75]} />
      <mesh geometry={nodes.Object_90.geometry} material={materials.tors} position={[0.277, -1.337, 1.209]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_92.geometry} material={materials.tors} position={[0.249, -1.287, 1.402]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_94.geometry} material={materials.tors} position={[0.342, -1.391, 1.382]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_96.geometry} material={materials.tors} position={[0.589, -0.958, 1.11]} rotation={[0, 0, 0.768]} />
      <mesh geometry={nodes.Object_98.geometry} material={materials.tors} position={[0.001, -1.229, 1.206]} />
      <mesh geometry={nodes.Object_100.geometry} material={materials.tors} position={[0.605, -0.963, 0.921]} rotation={[0, 0, 0.768]} />
      <mesh geometry={nodes.Object_102.geometry} material={materials.tors} position={[0.617, -0.97, 0.738]} rotation={[0, 0, 0.768]} />
      <mesh geometry={nodes.Object_104.geometry} material={materials.tors} position={[0, -0.879, 1.808]} rotation={[0.791, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_106.geometry} material={materials.tors} position={[1.043, 0.639, 0.436]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_108.geometry} material={materials.tors} position={[0.537, 0.262, -1.355]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_110.geometry} material={materials.tors} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_112.geometry} material={materials.tors} position={[0, -0.011, 0.129]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_114.geometry} material={materials.tors} position={[0, 1.102, -0.571]} rotation={[0.621, 0, 0]} />
      <mesh geometry={nodes.Object_116.geometry} material={materials.tors} position={[0.89, 1.336, -0.821]} rotation={[0.617, 0, 0]} />
      <mesh geometry={nodes.Object_118.geometry} material={materials.tors} position={[0, 0.119, -1.416]} rotation={[0.476, 0, 0]} />
      <mesh geometry={nodes.Object_120.geometry} material={materials.tors} position={[0.241, 0.758, 1.214]} rotation={[0.417, 0, 0]} />
      <mesh geometry={nodes.Object_122.geometry} material={materials.tors} position={[0.296, 0.694, 1.067]} rotation={[0.417, 0, -0.002]} />
      <mesh geometry={nodes.Object_124.geometry} material={materials.tors} position={[0, 0.776, 0.928]} />
      <mesh geometry={nodes.Object_126.geometry} material={materials.tors} position={[0.432, -0.276, 1.584]} rotation={[0.35, 0.84, -0.021]} />
      <mesh geometry={nodes.Object_128.geometry} material={materials.tors} position={[0.497, 0.538, 0.975]} rotation={[0.572, 0, 0]} />
      <mesh geometry={nodes.Object_130.geometry} material={materials.tors} position={[0.497, 0.38, 1.221]} rotation={[0.572, 0, 0]} />
      <mesh geometry={nodes.Object_132.geometry} material={materials.tors} position={[0.431, -0.74, 1.397]} rotation={[1.948, 0, 0]} />
      <mesh geometry={nodes.Object_134.geometry} material={materials.tors} position={[0.781, 0.198, -1.434]} rotation={[-0.365, 0, 0]} />
      <mesh geometry={nodes.Object_136.geometry} material={materials.tors} position={[0.781, -0.345, -1.358]} rotation={[-0.08, 0, 0]} />
      <mesh geometry={nodes.Object_138.geometry} material={materials.tors} position={[0.895, 1.127, -0.971]} rotation={[-0.955, 0, 0]} />
      <mesh geometry={nodes.Object_140.geometry} material={materials.tors} position={[0.85, -0.278, 1.086]} rotation={[0.415, 0, 0]} />
      <mesh geometry={nodes.Object_142.geometry} material={materials.tors} position={[0.787, 0.386, -1.216]} rotation={[-0.315, 0, 0]} />
      <mesh geometry={nodes.Object_144.geometry} material={materials.tors} position={[0, 0.908, -0.605]} />
      <mesh geometry={nodes.Object_146.geometry} material={materials.tors} position={[0.431, -0.74, 1.397]} rotation={[1.948, 0, 0]} />
      <mesh geometry={nodes.Object_148.geometry} material={materials.tors} position={[0.431, -0.74, 1.397]} rotation={[1.948, 0, 0]} />
      <mesh geometry={nodes.Object_150.geometry} material={materials.tors} position={[0, -0.174, 0.807]} rotation={[0.414, 0, 0]} />
      <mesh geometry={nodes.Object_152.geometry} material={materials.tors} position={[0, -0.174, 0.807]} rotation={[0.414, 0, 0]} />
      <mesh geometry={nodes.Object_154.geometry} material={materials.tors} position={[0, -0.174, 0.807]} rotation={[0.414, 0, 0]} />
      <mesh geometry={nodes.Object_156.geometry} material={materials.tors} position={[0, -1.293, -0.441]} />
      <mesh geometry={nodes.Object_158.geometry} material={materials.tors} position={[0, -1.293, -0.441]} />
      <mesh geometry={nodes.Object_160.geometry} material={materials.tors} position={[0, -1.816, -0.579]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_162.geometry} material={materials.tors} position={[0.505, -1.974, -0.515]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_164.geometry} material={materials.tors} position={[0.195, -2.021, -0.301]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_166.geometry} material={materials.tors} position={[0.195, -2.021, -0.562]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_168.geometry} material={materials.tors} position={[0, -1.286, -0.686]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_170.geometry} material={materials.tors} position={[-0.752, -1.295, -0.689]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_172.geometry} material={materials.tors} position={[0, -1.152, -0.528]} />
      <mesh geometry={nodes.Object_174.geometry} material={materials.tors} position={[0.267, -0.757, 0.067]} rotation={[-2.356, 0, 0]} />
      <mesh geometry={nodes.Object_176.geometry} material={materials.tors} position={[0, -0.864, -1.055]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_178.geometry} material={materials.tors} position={[0.212, -0.751, -1.282]} />
      <mesh geometry={nodes.Object_180.geometry} material={materials.tors} position={[0, -1.056, -1.045]} />
      <mesh geometry={nodes.Object_182.geometry} material={materials.tors} position={[0, -0.712, -0.621]} />
      <mesh geometry={nodes.Object_184.geometry} material={materials.tors} position={[0.332, -0.173, -0.542]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_186.geometry} material={materials.tors} position={[0.135, -0.33, -0.929]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_188.geometry} material={materials.tors} position={[0.221, -0.469, -0.967]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_190.geometry} material={materials.tors} position={[0, -0.362, -0.441]} />
      <mesh geometry={nodes.Object_192.geometry} material={materials.tors} position={[0.259, -0.838, -0.749]} />
      <mesh geometry={nodes.Object_194.geometry} material={materials.material_1} position={[1.245, -2.345, 0.706]} rotation={[0.929, 0, 0]} />
      <mesh geometry={nodes.Object_196.geometry} material={materials.material_1} position={[1.235, -2.545, 0.518]} />
      <mesh geometry={nodes.Object_198.geometry} material={materials.material_1} position={[0.7, -2.559, 0.234]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_200.geometry} material={materials.material_1} position={[1.246, -1.532, -0.399]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_202.geometry} material={materials.material_1} position={[1.235, -2.87, 0.244]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_204.geometry} material={materials.material_1} position={[1.235, -1.122, -0.624]} rotation={[-1.252, 0, 0]} />
      <mesh geometry={nodes.Object_206.geometry} material={materials.material_1} position={[1.849, -1.292, -0.527]} rotation={[0.318, 0, 0]} />
      <mesh geometry={nodes.Object_208.geometry} material={materials.material_1} position={[1.235, -1.122, -0.624]} rotation={[-1.252, 0, 0]} />
      <mesh geometry={nodes.Object_210.geometry} material={materials.material_1} position={[1.775, -1.035, -0.466]} />
      <mesh geometry={nodes.Object_212.geometry} material={materials.material_1} position={[1.775, -1.967, 0.858]} />
      <mesh geometry={nodes.Object_214.geometry} material={materials.material_1} position={[1.248, -1.554, -0.379]} />
      <mesh geometry={nodes.Object_216.geometry} material={materials.material_1} position={[1.24, -1.532, -1.14]} rotation={[-0.497, 0, 0]} />
      <mesh geometry={nodes.Object_218.geometry} material={materials.material_1} position={[1.249, -2.708, -0.126]} />
      <mesh geometry={nodes.Object_220.geometry} material={materials.material_1} position={[1.302, -2.731, -0.524]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_222.geometry} material={materials.material_1} position={[1.238, -2.297, 0]} rotation={[-0.461, 0, 0]} />
      <mesh geometry={nodes.Object_224.geometry} material={materials.material_1} position={[1.25, -3.257, -0.825]} rotation={[0.58, 0, 0]} />
      <mesh geometry={nodes.Object_226.geometry} material={materials.material_1} position={[1.232, -3.355, -0.129]} rotation={[0.551, 0, 0]} />
      <mesh geometry={nodes.Object_228.geometry} material={materials.material_1} position={[1.244, -3.066, -0.619]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_230.geometry} material={materials.material_1} position={[1.232, -3.068, -0.621]} rotation={[-0.297, 0, 0]} />
      <mesh geometry={nodes.Object_232.geometry} material={materials.material_1} position={[1.25, -2.939, -0.515]} rotation={[0.439, 0, 0]} />
      <mesh geometry={nodes.Object_234.geometry} material={materials.material_1} position={[1.232, -3.843, 0.06]} rotation={[0.568, 0, 0]} />
      <mesh geometry={nodes.Object_236.geometry} material={materials.material_1} position={[1.248, -3.208, -0.314]} rotation={[0.495, 0, 0]} />
      <mesh geometry={nodes.Object_238.geometry} material={materials.material_1} position={[1.232, -3.485, -0.016]} />
      <mesh geometry={nodes.Object_240.geometry} material={materials.material_1} position={[1.506, -4.04, 0.104]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_242.geometry} material={materials.material_1} position={[1.506, -3.586, -0.528]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_244.geometry} material={materials.material_1} position={[1.506, -3.94, -0.542]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_246.geometry} material={materials.material_1} position={[1.473, -4.005, -0.525]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_248.geometry} material={materials.material_1} position={[1.263, -2.719, -1.294]} rotation={[-0.629, 0, 0]} />
      <mesh geometry={nodes.Object_250.geometry} material={materials.material_1} position={[1.263, -3.054, -1.417]} rotation={[-1.875, 0, 0]} />
      <mesh geometry={nodes.Object_252.geometry} material={materials.material_1} position={[1.238, -2.964, -1.505]} />
      <mesh geometry={nodes.Object_254.geometry} material={materials.material_1} position={[1.253, -4.484, 0.106]} />
      <mesh geometry={nodes.Object_256.geometry} material={materials.material_1} position={[1.253, -4.393, 0.07]} />
      <mesh geometry={nodes.Object_258.geometry} material={materials.material_1} position={[1.253, -4.181, 0.07]} />
      <mesh geometry={nodes.Object_260.geometry} material={materials.material_1} position={[1.251, -4.186, 0.106]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_262.geometry} material={materials.material_1} position={[1.253, -4.477, 0.524]} />
      <mesh geometry={nodes.Object_264.geometry} material={materials.material_1} position={[1.253, -4.327, -0.345]} />
      <mesh geometry={nodes.Object_266.geometry} material={materials.material_1} position={[1.712, -4.405, -0.038]} />
      <mesh geometry={nodes.Object_268.geometry} material={materials.material_1} position={[1.791, -4.473, 0.106]} />
      <mesh geometry={nodes.Object_270.geometry} material={materials.material_1} position={[1.407, -4.552, 1.255]} />
      <mesh geometry={nodes.Object_272.geometry} material={materials.material_1} position={[1.651, -4.581, 0.604]} />
      <mesh geometry={nodes.Object_274.geometry} material={materials.material_1} position={[1.244, -4.429, 0.78]} />
      <mesh geometry={nodes.Object_276.geometry} material={materials.material_1} position={[1.244, -4.607, 1.107]} />
      <mesh geometry={nodes.Object_278.geometry} material={materials.material_1} position={[1.244, -4.351, 0.665]} />
      <mesh geometry={nodes.Object_280.geometry} material={materials.material_1} position={[1.244, -4.251, 0.924]} rotation={[1.313, 0, 0]} />
      <mesh geometry={nodes.Object_282.geometry} material={materials.material_1} position={[1.452, -4.553, 0.978]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_284.geometry} material={materials.material_1} position={[1.244, -4.498, 0.783]} />
      <mesh geometry={nodes.Object_286.geometry} material={materials.material_1} position={[1.929, -4.396, 0.971]} />
      <mesh geometry={nodes.Object_288.geometry} material={materials.material_1} position={[1.929, -4.396, 0.971]} />
      <mesh geometry={nodes.Object_290.geometry} material={materials.material_1} position={[1.54, -4.536, -0.373]} />
      <mesh geometry={nodes.Object_292.geometry} material={materials.material_1} position={[1.244, -4.397, -0.605]} rotation={[-0.724, 0, 0]} />
      <mesh geometry={nodes.Object_294.geometry} material={materials.material_1} position={[1.235, -4.418, -0.418]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_296.geometry} material={materials.material_1} position={[1.244, -4.498, -0.621]} />
      <mesh geometry={nodes.Object_298.geometry} material={materials.material} position={[1.567, 0.888, -0.972]} rotation={[0.233, 0, 0]} />
      <mesh geometry={nodes.Object_300.geometry} material={materials.material} position={[1.567, 0.888, -0.972]} rotation={[0.233, 0, 0]} />
      <mesh geometry={nodes.Object_302.geometry} material={materials.tors} position={[0, -0.616, -0.795]} />
      <mesh geometry={nodes.Object_304.geometry} material={materials.tors} position={[0.224, -1.498, 1.285]} />
      <mesh geometry={nodes.Object_306.geometry} material={materials.material} position={[1.814, -0.671, 1.412]} />
      <mesh geometry={nodes.Object_308.geometry} material={materials.material_1} position={[1.235, -2.321, 0.239]} />
      <mesh geometry={nodes.Object_310.geometry} material={materials.tors} position={[0, -0.182, -0.497]} />
      <mesh geometry={nodes.Object_312.geometry} material={materials.material_1} position={[2.785, 0.51, 0.595]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_314.geometry} material={materials.material_1} position={[1.244, -4.664, 0.971]} />
    </group>
  )
}

useGLTF.preload('/brobot.gltf')
