/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\3dmodels\new_cube\cube2.gltf 
Author: Tycho Magnetic Anomaly (https://sketchfab.com/Tycho_Magnetic_Anomaly)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/particles-cubed-6a3ef91e41914498b76585b21b7b2814
Title: Particles Cubed
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/3dmodels/new_cube/cube2.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.5}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Sphere_0" position={[-4.149, -2.29, 2.13]}>
                <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.material} />
              </group>
              <group name="Sphere001_1" position={[-2.328, 3.315, 3.255]}>
                <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.material} />
              </group>
              <group name="Sphere002_2" position={[-1.508, 4.227, -2.619]}>
                <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.material} />
              </group>
              <group name="Sphere003_3" position={[-3.33, -1.378, -3.743]}>
                <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.material} />
              </group>
              <group name="Sphere004_4" position={[2.328, -3.315, -3.255]}>
                <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.material} />
              </group>
              <group name="Sphere005_5" position={[4.149, 2.29, -2.13]}>
                <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.material} />
              </group>
              <group name="Sphere006_6" position={[2.249, -1.613, 4.397]}>
                <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.material} />
              </group>
              <group name="Sphere007_7" position={[4.117, 2.995, 1.039]}>
                <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.material} />
              </group>
              <group name="Sphere008_8" position={[-1.541, 4.932, 0.551]}>
                <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.material} />
              </group>
              <group name="Sphere009_9" position={[-3.408, 0.324, 3.909]}>
                <mesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials.material} />
              </group>
              <group name="Sphere010_10" position={[-4.117, -2.995, -1.039]}>
                <mesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials.material} />
              </group>
              <group name="Sphere011_11" position={[-2.249, 1.613, -4.397]}>
                <mesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials.material} />
              </group>
              <group name="Sphere012_12" position={[-4.41, 0.914, 2.591]}>
                <mesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials.material} />
              </group>
              <group name="Sphere013_13" position={[0.879, 3.507, 3.732]}>
                <mesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials.material} />
              </group>
              <group name="Sphere014_14" position={[1.698, 4.419, -2.142]}>
                <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials.material} />
              </group>
              <group name="Sphere015_15" position={[-3.591, 1.826, -3.282]}>
                <mesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials.material} />
              </group>
              <group name="Sphere016_16" position={[-0.879, -3.507, -3.732]}>
                <mesh name="Object_36" geometry={nodes.Object_36.geometry} material={materials.material} />
              </group>
              <group name="Sphere017_17" position={[4.41, -0.914, -2.591]}>
                <mesh name="Object_38" geometry={nodes.Object_38.geometry} material={materials.material} />
              </group>
              <group name="Cube003_21" scale={5.3}>
                <group name="Cube_18" scale={0.566}>
                  <mesh name="Object_42" geometry={nodes.Object_42.geometry} material={materials.hide2} />
                </group>
                <group name="Cube001_19" rotation={[0, Math.PI / 4, -Math.PI / 2]} scale={0.566}>
                  <mesh name="Object_44" geometry={nodes.Object_44.geometry} material={materials.hide2} />
                </group>
                <group name="Cube002_20" rotation={[-Math.PI / 4, 0, 0]} scale={0.566}>
                  <mesh name="Object_46" geometry={nodes.Object_46.geometry} material={materials.hide2} />
                </group>
                <mesh name="Object_40" geometry={nodes.Object_40.geometry} material={materials.hide} />
              </group>
              <group name="Sphere018_22" position={[3, 3, 3]}>
                <mesh name="Object_48" geometry={nodes.Object_48.geometry} material={materials.material_3} />
              </group>
              <group name="Sphere019_23" position={[3, 3, -3]}>
                <mesh name="Object_50" geometry={nodes.Object_50.geometry} material={materials.material_3} />
              </group>
              <group name="Sphere020_24" position={[-3, 3, -3]}>
                <mesh name="Object_52" geometry={nodes.Object_52.geometry} material={materials.material_3} />
              </group>
              <group name="Sphere021_25" position={[-3, 3, 3]}>
                <mesh name="Object_54" geometry={nodes.Object_54.geometry} material={materials.material_3} />
              </group>
              <group name="Sphere022_26" position={[-3, -3, 3]}>
                <mesh name="Object_56" geometry={nodes.Object_56.geometry} material={materials.material_3} />
              </group>
              <group name="Sphere023_27" position={[-3, -3, -3]}>
                <mesh name="Object_58" geometry={nodes.Object_58.geometry} material={materials.material_3} />
              </group>
              <group name="Sphere024_28" position={[4.243, -3, 0]}>
                <mesh name="Object_60" geometry={nodes.Object_60.geometry} material={materials.material_3} />
              </group>
              <group name="Sphere025_29" position={[0, -3, -4.243]}>
                <mesh name="Object_62" geometry={nodes.Object_62.geometry} material={materials.material_3} />
              </group>
              <group name="Sphere026_30" position={[0, 3, -4.243]}>
                <mesh name="Object_64" geometry={nodes.Object_64.geometry} material={materials.material_3} />
              </group>
              <group name="Sphere027_31" position={[4.243, 3, 0]}>
                <mesh name="Object_66" geometry={nodes.Object_66.geometry} material={materials.material_3} />
              </group>
              <group name="Sphere028_32" position={[0, 3, 4.243]}>
                <mesh name="Object_68" geometry={nodes.Object_68.geometry} material={materials.material_3} />
              </group>
              <group name="Sphere029_33" position={[-4.243, 3, 0]}>
                <mesh name="Object_70" geometry={nodes.Object_70.geometry} material={materials.material_3} />
              </group>
              <group name="Sphere030_34" position={[3, 4.243, 0]}>
                <mesh name="Object_72" geometry={nodes.Object_72.geometry} material={materials.material_3} />
              </group>
              <group name="Sphere031_35" position={[3, 0, -4.243]}>
                <mesh name="Object_74" geometry={nodes.Object_74.geometry} material={materials.material_3} />
              </group>
              <group name="Sphere032_36" position={[-3, 0, -4.243]}>
                <mesh name="Object_76" geometry={nodes.Object_76.geometry} material={materials.material_3} />
              </group>
              <group name="Sphere033_37" position={[-3, 4.243, 0]}>
                <mesh name="Object_78" geometry={nodes.Object_78.geometry} material={materials.material_3} />
              </group>
              <group name="Sphere034_38" position={[-3, 0, 4.243]}>
                <mesh name="Object_80" geometry={nodes.Object_80.geometry} material={materials.material_3} />
              </group>
              <group name="Sphere035_39" position={[-3, -4.243, 0]}>
                <mesh name="Object_82" geometry={nodes.Object_82.geometry} material={materials.material_3} />
              </group>
              <group name="Cube007_43" scale={5.3}>
                <group name="Cube004_40" scale={0.566}>
                  <mesh name="Object_86" geometry={nodes.Object_86.geometry} material={materials.hide2} />
                </group>
                <group name="Cube005_41" rotation={[0, Math.PI / 4, -Math.PI / 2]} scale={0.566}>
                  <mesh name="Object_88" geometry={nodes.Object_88.geometry} material={materials.hide2} />
                </group>
                <group name="Cube006_42" rotation={[-Math.PI / 4, 0, 0]} scale={0.566}>
                  <mesh name="Object_90" geometry={nodes.Object_90.geometry} material={materials.hide2} />
                </group>
                <mesh name="Object_84" geometry={nodes.Object_84.geometry} material={materials.hide} />
              </group>
              <group name="Sphere036_45" position={[-4.149, -2.29, 2.13]}>
                <mesh name="Object_94" geometry={nodes.Object_94.geometry} material={materials.material} />
              </group>
              <group name="Sphere037_46" position={[-2.328, 3.315, 3.255]}>
                <mesh name="Object_96" geometry={nodes.Object_96.geometry} material={materials.material} />
              </group>
              <group name="Sphere038_47" position={[-1.508, 4.227, -2.619]}>
                <mesh name="Object_98" geometry={nodes.Object_98.geometry} material={materials.material} />
              </group>
              <group name="Sphere039_48" position={[-3.33, -1.378, -3.743]}>
                <mesh name="Object_100" geometry={nodes.Object_100.geometry} material={materials.material} />
              </group>
              <group name="Sphere040_49" position={[2.328, -3.315, -3.255]}>
                <mesh name="Object_102" geometry={nodes.Object_102.geometry} material={materials.material} />
              </group>
              <group name="Sphere041_50" position={[4.149, 2.29, -2.13]}>
                <mesh name="Object_104" geometry={nodes.Object_104.geometry} material={materials.material} />
              </group>
              <group name="Sphere042_51" position={[2.249, -1.613, 4.397]}>
                <mesh name="Object_106" geometry={nodes.Object_106.geometry} material={materials.material} />
              </group>
              <group name="Sphere043_52" position={[4.117, 2.995, 1.039]}>
                <mesh name="Object_108" geometry={nodes.Object_108.geometry} material={materials.material} />
              </group>
              <group name="Sphere044_53" position={[-1.541, 4.932, 0.551]}>
                <mesh name="Object_110" geometry={nodes.Object_110.geometry} material={materials.material} />
              </group>
              <group name="Sphere045_54" position={[-3.408, 0.324, 3.909]}>
                <mesh name="Object_112" geometry={nodes.Object_112.geometry} material={materials.material} />
              </group>
              <group name="Sphere046_55" position={[-4.117, -2.995, -1.039]}>
                <mesh name="Object_114" geometry={nodes.Object_114.geometry} material={materials.material} />
              </group>
              <group name="Sphere047_56" position={[-2.249, 1.613, -4.397]}>
                <mesh name="Object_116" geometry={nodes.Object_116.geometry} material={materials.material} />
              </group>
              <group name="Sphere048_57" position={[-4.41, 0.914, 2.591]}>
                <mesh name="Object_118" geometry={nodes.Object_118.geometry} material={materials.material} />
              </group>
              <group name="Sphere049_58" position={[0.879, 3.507, 3.732]}>
                <mesh name="Object_120" geometry={nodes.Object_120.geometry} material={materials.material} />
              </group>
              <group name="Sphere050_59" position={[1.698, 4.419, -2.142]}>
                <mesh name="Object_122" geometry={nodes.Object_122.geometry} material={materials.material} />
              </group>
              <group name="Sphere051_60" position={[-3.591, 1.826, -3.282]}>
                <mesh name="Object_124" geometry={nodes.Object_124.geometry} material={materials.material} />
              </group>
              <group name="Sphere052_61" position={[-0.879, -3.507, -3.732]}>
                <mesh name="Object_126" geometry={nodes.Object_126.geometry} material={materials.material} />
              </group>
              <group name="Sphere053_62" position={[4.41, -0.914, -2.591]}>
                <mesh name="Object_128" geometry={nodes.Object_128.geometry} material={materials.material} />
              </group>
              <group name="Sphere054_63" position={[3, 3, 3]}>
                <mesh name="Object_130" geometry={nodes.Object_130.geometry} material={materials.material_3} />
              </group>
              <group name="Sphere055_64" position={[3, 3, -3]}>
                <mesh name="Object_132" geometry={nodes.Object_132.geometry} material={materials.material_3} />
              </group>
              <group name="Sphere056_65" position={[-3, 3, -3]}>
                <mesh name="Object_134" geometry={nodes.Object_134.geometry} material={materials.material_3} />
              </group>
              <group name="Sphere057_66" position={[-3, 3, 3]}>
                <mesh name="Object_136" geometry={nodes.Object_136.geometry} material={materials.material_3} />
              </group>
              <group name="Sphere058_67" position={[-3, -3, 3]}>
                <mesh name="Object_138" geometry={nodes.Object_138.geometry} material={materials.material_3} />
              </group>
              <group name="Sphere059_68" position={[-3, -3, -3]}>
                <mesh name="Object_140" geometry={nodes.Object_140.geometry} material={materials.material_3} />
              </group>
              <group name="Sphere060_69" position={[4.243, -3, 0]}>
                <mesh name="Object_142" geometry={nodes.Object_142.geometry} material={materials.material_3} />
              </group>
              <group name="Sphere061_70" position={[0, -3, -4.243]}>
                <mesh name="Object_144" geometry={nodes.Object_144.geometry} material={materials.material_3} />
              </group>
              <group name="Sphere062_71" position={[0, 3, -4.243]}>
                <mesh name="Object_146" geometry={nodes.Object_146.geometry} material={materials.material_3} />
              </group>
              <group name="Sphere063_72" position={[4.243, 3, 0]}>
                <mesh name="Object_148" geometry={nodes.Object_148.geometry} material={materials.material_3} />
              </group>
              <group name="Sphere064_73" position={[0, 3, 4.243]}>
                <mesh name="Object_150" geometry={nodes.Object_150.geometry} material={materials.material_3} />
              </group>
              <group name="Sphere065_74" position={[-4.243, 3, 0]}>
                <mesh name="Object_152" geometry={nodes.Object_152.geometry} material={materials.material_3} />
              </group>
              <group name="Sphere066_75" position={[3, 4.243, 0]}>
                <mesh name="Object_154" geometry={nodes.Object_154.geometry} material={materials.material_3} />
              </group>
              <group name="Sphere067_76" position={[3, 0, -4.243]}>
                <mesh name="Object_156" geometry={nodes.Object_156.geometry} material={materials.material_3} />
              </group>
              <group name="Sphere068_77" position={[-3, 0, -4.243]}>
                <mesh name="Object_158" geometry={nodes.Object_158.geometry} material={materials.material_3} />
              </group>
              <group name="Sphere069_78" position={[-3, 4.243, 0]}>
                <mesh name="Object_160" geometry={nodes.Object_160.geometry} material={materials.material_3} />
              </group>
              <group name="Sphere070_79" position={[-3, 0, 4.243]}>
                <mesh name="Object_162" geometry={nodes.Object_162.geometry} material={materials.material_3} />
              </group>
              <group name="Sphere071_80" position={[-3, -4.243, 0]}>
                <mesh name="Object_164" geometry={nodes.Object_164.geometry} material={materials.material_3} />
              </group>
              <group name="Cube008_44" rotation={[1.769, -0.309, 1.715]}>
                <mesh name="Object_92" geometry={nodes.Object_92.geometry} material={materials.hide} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/3dmodels/new_cube/cube2.gltf')
