/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\3dmodels\new_cube\cube3.gltf 
Author: VIS-All-3D (https://sketchfab.com/VIS-All)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/placeholder-cube-red-7176bf40d9a246c7b3a85c679fefa60b
Title: Placeholder-Cube Red
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/3dmodels/new_cube/cube3.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Cube_cell013_cell_0" position={[0.784, 0.279, 0.705]}>
                <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell001_1" position={[0.337, 0.68, -0.735]}>
                <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell002_2" position={[0.129, 0.697, -0.157]}>
                <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell003_3" position={[0.796, 0.698, -0.524]}>
                <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell004_4" position={[0.407, 0.169, -0.767]}>
                <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell005_5" position={[0.054, 0.319, -0.731]}>
                <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell006_6" position={[0.141, 0.137, -0.165]}>
                <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell007_7" position={[0.491, 0.306, -0.353]}>
                <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell008_8" position={[0.011, 0.248, -0.343]}>
                <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell009_9" position={[0.859, -0.39, -0.166]}>
                <mesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell010_10" position={[0.102, -0.233, -0.392]}>
                <mesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell011_11" position={[0.272, -0.781, -0.204]}>
                <mesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell012_12" position={[0.331, -0.623, -0.726]}>
                <mesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell013_13" position={[0.537, -0.206, -0.258]}>
                <mesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell015_14" position={[0.649, -0.434, -0.771]}>
                <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell016_15" position={[0.611, -0.966, -0.299]}>
                <mesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell017_16" position={[0.897, 0.216, 0.197]}>
                <mesh name="Object_36" geometry={nodes.Object_36.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell018_17" position={[0.219, 0.792, 0.49]}>
                <mesh name="Object_38" geometry={nodes.Object_38.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell019_18" position={[0.265, 0.334, 0.77]}>
                <mesh name="Object_40" geometry={nodes.Object_40.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell020_19" position={[0.547, 0.273, 0.278]}>
                <mesh name="Object_42" geometry={nodes.Object_42.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell021_20" position={[0.172, 0.236, 0.296]}>
                <mesh name="Object_44" geometry={nodes.Object_44.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell022_21" position={[0.791, 0.674, 0.26]}>
                <mesh name="Object_46" geometry={nodes.Object_46.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell023_22" position={[0.645, 0.712, 0.738]}>
                <mesh name="Object_48" geometry={nodes.Object_48.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell024_23" position={[0.529, -0.329, 0.252]}>
                <mesh name="Object_50" geometry={nodes.Object_50.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell025_24" position={[0.756, -0.762, 0.573]}>
                <mesh name="Object_52" geometry={nodes.Object_52.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell026_25" position={[0.381, -0.76, 0.253]}>
                <mesh name="Object_54" geometry={nodes.Object_54.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell027_26" position={[0.731, -0.271, 0.68]}>
                <mesh name="Object_56" geometry={nodes.Object_56.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell028_27" position={[0.321, -0.665, 0.743]}>
                <mesh name="Object_58" geometry={nodes.Object_58.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell029_28" position={[0.221, -0.293, 0.694]}>
                <mesh name="Object_60" geometry={nodes.Object_60.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell030_29" position={[0.881, -0.563, 0.164]}>
                <mesh name="Object_62" geometry={nodes.Object_62.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell031_30" position={[0.169, -0.223, 0.147]}>
                <mesh name="Object_64" geometry={nodes.Object_64.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell032_31" position={[-0.303, 0.735, -0.38]}>
                <mesh name="Object_66" geometry={nodes.Object_66.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell033_32" position={[-0.296, 0.74, -0.718]}>
                <mesh name="Object_68" geometry={nodes.Object_68.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell034_33" position={[-0.313, 0.323, -0.705]}>
                <mesh name="Object_70" geometry={nodes.Object_70.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell035_34" position={[-0.758, 0.402, -0.313]}>
                <mesh name="Object_72" geometry={nodes.Object_72.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell036_35" position={[-0.298, 0.224, -0.322]}>
                <mesh name="Object_74" geometry={nodes.Object_74.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell037_36" position={[-0.293, -0.799, 0.417]}>
                <mesh name="Object_76" geometry={nodes.Object_76.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell038_37" position={[-0.077, -0.914, 0.468]}>
                <mesh name="Object_78" geometry={nodes.Object_78.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell039_38" position={[-0.011, -0.769, 0.813]}>
                <mesh name="Object_80" geometry={nodes.Object_80.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell040_39" position={[-0.079, -0.729, 0.564]}>
                <mesh name="Object_82" geometry={nodes.Object_82.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell041_40" position={[-0.161, -0.741, 0.055]}>
                <mesh name="Object_84" geometry={nodes.Object_84.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell042_41" position={[-0.378, -0.879, 0.046]}>
                <mesh name="Object_86" geometry={nodes.Object_86.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell043_42" position={[-0.304, -0.988, 0.114]}>
                <mesh name="Object_88" geometry={nodes.Object_88.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell044_43" position={[-0.26, -0.693, 0.245]}>
                <mesh name="Object_90" geometry={nodes.Object_90.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell045_44" position={[-0.732, -0.093, 0.297]}>
                <mesh name="Object_92" geometry={nodes.Object_92.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell046_45" position={[-0.846, -0.354, 0.242]}>
                <mesh name="Object_94" geometry={nodes.Object_94.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell047_46" position={[-0.577, -0.445, 0.306]}>
                <mesh name="Object_96" geometry={nodes.Object_96.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell048_47" position={[-0.878, -0.354, 0.592]}>
                <mesh name="Object_98" geometry={nodes.Object_98.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell049_48" position={[-0.57, -0.512, 0.494]}>
                <mesh name="Object_100" geometry={nodes.Object_100.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell050_49" position={[-0.49, -0.006, 0.278]}>
                <mesh name="Object_102" geometry={nodes.Object_102.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell051_50" position={[-0.609, -0.156, 0.509]}>
                <mesh name="Object_104" geometry={nodes.Object_104.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell052_51" position={[-0.453, -0.37, 0.775]}>
                <mesh name="Object_106" geometry={nodes.Object_106.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell053_52" position={[-0.127, -0.374, 0.612]}>
                <mesh name="Object_108" geometry={nodes.Object_108.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell055_53" position={[-0.046, -0.253, 0.181]}>
                <mesh name="Object_110" geometry={nodes.Object_110.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell056_54" position={[-0.02, -0.078, -0.029]}>
                <mesh name="Object_112" geometry={nodes.Object_112.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell057_55" position={[-0.224, -0.072, 0.219]}>
                <mesh name="Object_114" geometry={nodes.Object_114.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell058_56" position={[-0.026, -0.042, 0.225]}>
                <mesh name="Object_116" geometry={nodes.Object_116.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell059_57" position={[-0.251, -0.336, 0.338]}>
                <mesh name="Object_118" geometry={nodes.Object_118.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell060_58" position={[-0.123, -0.129, 0.66]}>
                <mesh name="Object_120" geometry={nodes.Object_120.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell061_59" position={[-0.688, -0.337, 0.1]}>
                <mesh name="Object_122" geometry={nodes.Object_122.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell062_60" position={[-0.826, -0.119, -0.022]}>
                <mesh name="Object_124" geometry={nodes.Object_124.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell063_61" position={[-0.665, -0.375, -0.037]}>
                <mesh name="Object_126" geometry={nodes.Object_126.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell064_62" position={[-0.854, -0.373, -0.005]}>
                <mesh name="Object_128" geometry={nodes.Object_128.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell065_63" position={[-0.966, -0.104, -0.015]}>
                <mesh name="Object_130" geometry={nodes.Object_130.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell066_64" position={[-0.858, -0.129, 0.104]}>
                <mesh name="Object_132" geometry={nodes.Object_132.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell067_65" position={[-0.912, -0.375, 0.118]}>
                <mesh name="Object_134" geometry={nodes.Object_134.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell068_66" position={[-0.653, -0.128, 0.023]}>
                <mesh name="Object_136" geometry={nodes.Object_136.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell069_67" position={[-0.151, -0.419, -0.002]}>
                <mesh name="Object_138" geometry={nodes.Object_138.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell070_68" position={[-0.423, -0.423, 0.188]}>
                <mesh name="Object_140" geometry={nodes.Object_140.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell071_69" position={[-0.114, -0.055, -0.085]}>
                <mesh name="Object_142" geometry={nodes.Object_142.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell072_70" position={[-0.318, -0.116, 0.035]}>
                <mesh name="Object_144" geometry={nodes.Object_144.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell073_71" position={[-0.457, -0.372, 0.018]}>
                <mesh name="Object_146" geometry={nodes.Object_146.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell074_72" position={[-0.492, -0.097, 0.111]}>
                <mesh name="Object_148" geometry={nodes.Object_148.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell075_73" position={[-0.21, -0.119, -0.039]}>
                <mesh name="Object_150" geometry={nodes.Object_150.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell076_74" position={[-0.085, -0.144, -0.078]}>
                <mesh name="Object_152" geometry={nodes.Object_152.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell077_75" position={[-0.373, -0.537, 0.922]}>
                <mesh name="Object_154" geometry={nodes.Object_154.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell078_76" position={[-0.574, -0.863, 0.701]}>
                <mesh name="Object_156" geometry={nodes.Object_156.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell079_77" position={[-0.383, -0.944, 0.939]}>
                <mesh name="Object_158" geometry={nodes.Object_158.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell080_78" position={[-0.177, -0.945, 0.788]}>
                <mesh name="Object_160" geometry={nodes.Object_160.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell081_79" position={[-0.154, -0.738, 0.869]}>
                <mesh name="Object_162" geometry={nodes.Object_162.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell082_80" position={[-0.417, -0.775, 0.793]}>
                <mesh name="Object_164" geometry={nodes.Object_164.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell083_81" position={[-0.797, -0.717, 0.773]}>
                <mesh name="Object_166" geometry={nodes.Object_166.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell084_82" position={[-0.063, -0.568, 0.942]}>
                <mesh name="Object_168" geometry={nodes.Object_168.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell085_83" position={[-0.155, 0.01, -0.047]}>
                <mesh name="Object_170" geometry={nodes.Object_170.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell086_84" position={[-0.205, 0.008, 0.047]}>
                <mesh name="Object_172" geometry={nodes.Object_172.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell087_85" position={[-0.073, -0.023, -0.082]}>
                <mesh name="Object_174" geometry={nodes.Object_174.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell088_86" position={[-0.061, -0.041, -0.056]}>
                <mesh name="Object_176" geometry={nodes.Object_176.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell089_87" position={[-0.047, -0.013, -0.046]}>
                <mesh name="Object_178" geometry={nodes.Object_178.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell090_88" position={[-0.102, 0.001, -0.068]}>
                <mesh name="Object_180" geometry={nodes.Object_180.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell091_89" position={[-0.128, -0.001, -0.015]}>
                <mesh name="Object_182" geometry={nodes.Object_182.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell093_90" position={[-0.651, -0.622, 0.175]}>
                <mesh name="Object_184" geometry={nodes.Object_184.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell094_91" position={[-0.796, -0.87, 0.07]}>
                <mesh name="Object_186" geometry={nodes.Object_186.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell095_92" position={[-0.651, -0.898, 0.277]}>
                <mesh name="Object_188" geometry={nodes.Object_188.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell096_93" position={[-0.583, -0.71, 0.263]}>
                <mesh name="Object_190" geometry={nodes.Object_190.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell097_94" position={[-0.531, -0.751, -0.09]}>
                <mesh name="Object_192" geometry={nodes.Object_192.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell098_95" position={[-0.911, -0.595, 0.086]}>
                <mesh name="Object_194" geometry={nodes.Object_194.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell099_96" position={[-0.868, -0.771, 0.338]}>
                <mesh name="Object_196" geometry={nodes.Object_196.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell100_97" position={[-0.586, -0.754, -0.025]}>
                <mesh name="Object_198" geometry={nodes.Object_198.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell101_98" position={[-0.114, 0.585, 0.214]}>
                <mesh name="Object_200" geometry={nodes.Object_200.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell102_99" position={[-0.122, 0.84, 0.014]}>
                <mesh name="Object_202" geometry={nodes.Object_202.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell103_100" position={[-0.14, 0.593, 0.031]}>
                <mesh name="Object_204" geometry={nodes.Object_204.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell104_101" position={[-0.01, 0.568, 0.028]}>
                <mesh name="Object_206" geometry={nodes.Object_206.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell105_102" position={[-0.428, 0.912, 0.15]}>
                <mesh name="Object_208" geometry={nodes.Object_208.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell106_103" position={[-0.332, 0.712, 0.388]}>
                <mesh name="Object_210" geometry={nodes.Object_210.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell107_104" position={[-0.374, 0.67, 0.121]}>
                <mesh name="Object_212" geometry={nodes.Object_212.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell108_105" position={[-0.116, 0.76, 0.146]}>
                <mesh name="Object_214" geometry={nodes.Object_214.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell110_106" position={[-0.769, 0.064, 0.089]}>
                <mesh name="Object_216" geometry={nodes.Object_216.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell111_107" position={[-0.792, 0.174, 0.076]}>
                <mesh name="Object_218" geometry={nodes.Object_218.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell112_108" position={[-0.67, 0.067, 0.809]}>
                <mesh name="Object_220" geometry={nodes.Object_220.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell113_109" position={[-0.66, 0.147, 0.5]}>
                <mesh name="Object_222" geometry={nodes.Object_222.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell114_110" position={[-0.875, 0.054, -0.077]}>
                <mesh name="Object_224" geometry={nodes.Object_224.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell115_111" position={[-0.545, 0.081, 0.781]}>
                <mesh name="Object_226" geometry={nodes.Object_226.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell116_112" position={[-0.59, 0.168, 0.06]}>
                <mesh name="Object_228" geometry={nodes.Object_228.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell117_113" position={[-0.78, 0.819, 0.274]}>
                <mesh name="Object_230" geometry={nodes.Object_230.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell118_114" position={[-0.624, 0.41, 0.108]}>
                <mesh name="Object_232" geometry={nodes.Object_232.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell119_115" position={[-0.572, 0.523, 0.357]}>
                <mesh name="Object_234" geometry={nodes.Object_234.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell120_116" position={[-0.527, 0.501, -0.038]}>
                <mesh name="Object_236" geometry={nodes.Object_236.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell121_117" position={[-0.813, 0.894, 0.021]}>
                <mesh name="Object_238" geometry={nodes.Object_238.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell122_118" position={[-0.82, 0.416, 0.376]}>
                <mesh name="Object_240" geometry={nodes.Object_240.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell123_119" position={[-0.861, 0.512, 0.095]}>
                <mesh name="Object_242" geometry={nodes.Object_242.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell124_120" position={[-0.579, 0.627, 0.058]}>
                <mesh name="Object_244" geometry={nodes.Object_244.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell125_121" position={[-0.254, 0.441, 0.38]}>
                <mesh name="Object_246" geometry={nodes.Object_246.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell126_122" position={[-0.113, 0.296, 0.649]}>
                <mesh name="Object_248" geometry={nodes.Object_248.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell127_123" position={[-0.329, 0.168, 0.091]}>
                <mesh name="Object_250" geometry={nodes.Object_250.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell128_124" position={[-0.159, 0.341, 0.176]}>
                <mesh name="Object_252" geometry={nodes.Object_252.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell129_125" position={[-0.35, 0.23, 0.492]}>
                <mesh name="Object_254" geometry={nodes.Object_254.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell130_126" position={[-0.294, 0.111, 0.847]}>
                <mesh name="Object_256" geometry={nodes.Object_256.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell131_127" position={[-0.271, 0.415, 0.617]}>
                <mesh name="Object_258" geometry={nodes.Object_258.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell132_128" position={[-0.004, 0.458, 0.266]}>
                <mesh name="Object_260" geometry={nodes.Object_260.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell133_129" position={[-0.141, 0.571, 0.937]}>
                <mesh name="Object_262" geometry={nodes.Object_262.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell134_130" position={[-0.397, 0.602, 0.765]}>
                <mesh name="Object_264" geometry={nodes.Object_264.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell135_131" position={[-0.583, 0.847, 0.668]}>
                <mesh name="Object_266" geometry={nodes.Object_266.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell136_132" position={[-0.754, 0.096, 0.905]}>
                <mesh name="Object_268" geometry={nodes.Object_268.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell137_133" position={[-0.909, 0.853, 0.648]}>
                <mesh name="Object_270" geometry={nodes.Object_270.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell138_134" position={[-0.378, 0.265, 0.899]}>
                <mesh name="Object_272" geometry={nodes.Object_272.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell139_135" position={[-0.697, 0.384, 0.8]}>
                <mesh name="Object_274" geometry={nodes.Object_274.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell140_136" position={[-0.254, 0.858, 0.88]}>
                <mesh name="Object_276" geometry={nodes.Object_276.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell141_137" position={[-0.079, 0.598, 0.778]}>
                <mesh name="Object_278" geometry={nodes.Object_278.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell142_138" position={[-0.044, 0.595, 0.447]}>
                <mesh name="Object_280" geometry={nodes.Object_280.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell143_139" position={[-0.053, 0.454, 0.879]}>
                <mesh name="Object_282" geometry={nodes.Object_282.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell144_140" position={[-0.038, 0.88, 0.913]}>
                <mesh name="Object_284" geometry={nodes.Object_284.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell145_141" position={[-0.114, 0.907, 0.854]}>
                <mesh name="Object_286" geometry={nodes.Object_286.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell146_142" position={[-0.053, 0.83, 0.628]}>
                <mesh name="Object_288" geometry={nodes.Object_288.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell147_143" position={[0.005, 0.831, 0.249]}>
                <mesh name="Object_290" geometry={nodes.Object_290.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell148_144" position={[-0.068, 0.988, 0.937]}>
                <mesh name="Object_292" geometry={nodes.Object_292.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell149_145" position={[-0.902, 0.218, 0.021]}>
                <mesh name="Object_294" geometry={nodes.Object_294.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell151_146" position={[-0.902, 0.166, 0.559]}>
                <mesh name="Object_296" geometry={nodes.Object_296.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell152_147" position={[-0.94, 0.107, 0.106]}>
                <mesh name="Object_298" geometry={nodes.Object_298.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell153_148" position={[-0.996, 0.092, -0.055]}>
                <mesh name="Object_300" geometry={nodes.Object_300.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell154_149" position={[-0.967, 0.22, -0.053]}>
                <mesh name="Object_302" geometry={nodes.Object_302.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell155_150" position={[-0.927, 0.24, 0.163]}>
                <mesh name="Object_304" geometry={nodes.Object_304.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell156_151" position={[-0.992, 0.267, -0.057]}>
                <mesh name="Object_306" geometry={nodes.Object_306.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell157_152" position={[-0.207, 0.91, 0.594]}>
                <mesh name="Object_308" geometry={nodes.Object_308.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell158_153" position={[-0.183, 0.658, 0.511]}>
                <mesh name="Object_310" geometry={nodes.Object_310.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell159_154" position={[-0.081, 0.759, 0.271]}>
                <mesh name="Object_312" geometry={nodes.Object_312.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell160_155" position={[-0.072, 0.926, 0.2]}>
                <mesh name="Object_314" geometry={nodes.Object_314.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell161_156" position={[-0.178, 0.811, 0.625]}>
                <mesh name="Object_316" geometry={nodes.Object_316.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell162_157" position={[0.002, 0.899, 0.051]}>
                <mesh name="Object_318" geometry={nodes.Object_318.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell163_158" position={[0.005, 0.96, 0.023]}>
                <mesh name="Object_320" geometry={nodes.Object_320.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell165_159" position={[-0.961, -0.013, -0.413]}>
                <mesh name="Object_322" geometry={nodes.Object_322.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell167_160" position={[-0.897, -0.027, -0.229]}>
                <mesh name="Object_324" geometry={nodes.Object_324.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell168_161" position={[-0.655, -0.023, -0.22]}>
                <mesh name="Object_326" geometry={nodes.Object_326.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell169_162" position={[-0.952, -0.05, -0.436]}>
                <mesh name="Object_328" geometry={nodes.Object_328.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell170_163" position={[-0.622, -0.03, -0.409]}>
                <mesh name="Object_330" geometry={nodes.Object_330.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell171_164" position={[-0.644, -0.069, -0.482]}>
                <mesh name="Object_332" geometry={nodes.Object_332.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell172_165" position={[-0.81, -0.026, -0.41]}>
                <mesh name="Object_334" geometry={nodes.Object_334.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell173_166" position={[-0.236, -0.63, -0.894]}>
                <mesh name="Object_336" geometry={nodes.Object_336.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell174_167" position={[-0.471, -0.861, -0.772]}>
                <mesh name="Object_338" geometry={nodes.Object_338.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell175_168" position={[-0.251, -0.842, -0.84]}>
                <mesh name="Object_340" geometry={nodes.Object_340.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell176_169" position={[-0.162, -0.642, -0.639]}>
                <mesh name="Object_342" geometry={nodes.Object_342.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell177_170" position={[-0.734, -0.961, -0.945]}>
                <mesh name="Object_344" geometry={nodes.Object_344.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell178_171" position={[-0.389, -0.588, -0.681]}>
                <mesh name="Object_346" geometry={nodes.Object_346.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell179_172" position={[-0.673, -0.806, -0.897]}>
                <mesh name="Object_348" geometry={nodes.Object_348.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell180_173" position={[-0.557, -0.635, -0.772]}>
                <mesh name="Object_350" geometry={nodes.Object_350.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell181_174" position={[-0.243, -0.584, -0.321]}>
                <mesh name="Object_352" geometry={nodes.Object_352.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell182_175" position={[-0.392, -0.625, -0.48]}>
                <mesh name="Object_354" geometry={nodes.Object_354.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell183_176" position={[-0.43, -0.813, -0.254]}>
                <mesh name="Object_356" geometry={nodes.Object_356.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell184_177" position={[-0.2, -0.83, -0.461]}>
                <mesh name="Object_358" geometry={nodes.Object_358.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell185_178" position={[-0.438, -0.873, -0.457]}>
                <mesh name="Object_360" geometry={nodes.Object_360.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell186_179" position={[-0.529, -0.593, -0.385]}>
                <mesh name="Object_362" geometry={nodes.Object_362.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell187_180" position={[-0.18, -0.861, -0.21]}>
                <mesh name="Object_364" geometry={nodes.Object_364.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell189_181" position={[-0.137, -0.334, -0.884]}>
                <mesh name="Object_366" geometry={nodes.Object_366.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell190_182" position={[-0.406, -0.149, -0.763]}>
                <mesh name="Object_368" geometry={nodes.Object_368.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell191_183" position={[-0.124, -0.148, -0.771]}>
                <mesh name="Object_370" geometry={nodes.Object_370.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell192_184" position={[-0.251, -0.349, -0.67]}>
                <mesh name="Object_372" geometry={nodes.Object_372.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell193_185" position={[-0.211, -0.122, -0.795]}>
                <mesh name="Object_374" geometry={nodes.Object_374.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell194_186" position={[-0.385, -0.341, -0.833]}>
                <mesh name="Object_376" geometry={nodes.Object_376.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell195_187" position={[-0.252, -0.124, -0.621]}>
                <mesh name="Object_378" geometry={nodes.Object_378.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell196_188" position={[-0.212, -0.334, -0.517]}>
                <mesh name="Object_380" geometry={nodes.Object_380.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell197_189" position={[-0.187, -0.112, -0.346]}>
                <mesh name="Object_382" geometry={nodes.Object_382.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell198_190" position={[-0.205, -0.421, -0.295]}>
                <mesh name="Object_384" geometry={nodes.Object_384.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell199_191" position={[-0.442, -0.394, -0.475]}>
                <mesh name="Object_386" geometry={nodes.Object_386.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell200_192" position={[-0.446, -0.1, -0.472]}>
                <mesh name="Object_388" geometry={nodes.Object_388.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell201_193" position={[-0.471, -0.038, -0.211]}>
                <mesh name="Object_390" geometry={nodes.Object_390.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell202_194" position={[-0.415, -0.286, -0.224]}>
                <mesh name="Object_392" geometry={nodes.Object_392.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell203_195" position={[-0.526, -0.013, -0.149]}>
                <mesh name="Object_394" geometry={nodes.Object_394.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell204_196" position={[-0.619, -0.365, -0.478]}>
                <mesh name="Object_396" geometry={nodes.Object_396.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell205_197" position={[-0.771, -0.46, -0.214]}>
                <mesh name="Object_398" geometry={nodes.Object_398.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell206_198" position={[-0.644, -0.471, -0.44]}>
                <mesh name="Object_400" geometry={nodes.Object_400.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell207_199" position={[-0.882, -0.207, -0.201]}>
                <mesh name="Object_402" geometry={nodes.Object_402.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell208_200" position={[-0.679, -0.244, -0.245]}>
                <mesh name="Object_404" geometry={nodes.Object_404.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell209_201" position={[-0.837, -0.199, -0.417]}>
                <mesh name="Object_406" geometry={nodes.Object_406.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell210_202" position={[-0.889, -0.419, -0.406]}>
                <mesh name="Object_408" geometry={nodes.Object_408.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell211_203" position={[-0.657, -0.107, -0.307]}>
                <mesh name="Object_410" geometry={nodes.Object_410.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell212_204" position={[-0.73, -0.403, -0.768]}>
                <mesh name="Object_412" geometry={nodes.Object_412.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell213_205" position={[-0.57, 0.005, -0.563]}>
                <mesh name="Object_414" geometry={nodes.Object_414.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell214_206" position={[-0.925, -0.196, -0.713]}>
                <mesh name="Object_416" geometry={nodes.Object_416.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell216_207" position={[-0.798, -0.108, -0.744]}>
                <mesh name="Object_418" geometry={nodes.Object_418.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell217_208" position={[-0.609, -0.097, -0.771]}>
                <mesh name="Object_420" geometry={nodes.Object_420.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell218_209" position={[-0.601, -0.103, -0.596]}>
                <mesh name="Object_422" geometry={nodes.Object_422.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell219_210" position={[-0.861, -0.572, -0.885]}>
                <mesh name="Object_424" geometry={nodes.Object_424.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell220_211" position={[-0.916, -0.793, -0.801]}>
                <mesh name="Object_426" geometry={nodes.Object_426.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell221_212" position={[-0.638, -0.776, -0.21]}>
                <mesh name="Object_428" geometry={nodes.Object_428.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell222_213" position={[-0.744, -0.893, -0.564]}>
                <mesh name="Object_430" geometry={nodes.Object_430.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell223_214" position={[-0.8, -0.686, -0.553]}>
                <mesh name="Object_432" geometry={nodes.Object_432.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell224_215" position={[-0.918, -0.887, -0.725]}>
                <mesh name="Object_434" geometry={nodes.Object_434.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell225_216" position={[-0.899, -0.734, -0.34]}>
                <mesh name="Object_436" geometry={nodes.Object_436.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell226_217" position={[-0.917, -0.876, -0.312]}>
                <mesh name="Object_438" geometry={nodes.Object_438.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell227_218" position={[-0.956, -0.968, -0.986]}>
                <mesh name="Object_440" geometry={nodes.Object_440.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell228_219" position={[-0.311, 0.017, -0.206]}>
                <mesh name="Object_442" geometry={nodes.Object_442.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell229_220" position={[-0.696, 0.033, -0.163]}>
                <mesh name="Object_444" geometry={nodes.Object_444.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell230_221" position={[-0.169, -0.008, -0.166]}>
                <mesh name="Object_446" geometry={nodes.Object_446.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell231_222" position={[-0.545, 0.029, -0.445]}>
                <mesh name="Object_448" geometry={nodes.Object_448.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell232_223" position={[-0.411, 0.031, -0.385]}>
                <mesh name="Object_450" geometry={nodes.Object_450.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell233_224" position={[-0.666, 0.082, -0.344]}>
                <mesh name="Object_452" geometry={nodes.Object_452.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell234_225" position={[-0.574, 0.096, -0.432]}>
                <mesh name="Object_454" geometry={nodes.Object_454.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell235_226" position={[-0.557, 0.066, -0.23]}>
                <mesh name="Object_456" geometry={nodes.Object_456.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell236_227" position={[-0.795, 0.135, -0.852]}>
                <mesh name="Object_458" geometry={nodes.Object_458.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell237_228" position={[-0.673, 0.309, -0.631]}>
                <mesh name="Object_460" geometry={nodes.Object_460.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell238_229" position={[-0.894, 0.1, -0.58]}>
                <mesh name="Object_462" geometry={nodes.Object_462.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell239_230" position={[-0.656, 0.386, -0.891]}>
                <mesh name="Object_464" geometry={nodes.Object_464.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell240_231" position={[-0.874, 0.323, -0.653]}>
                <mesh name="Object_466" geometry={nodes.Object_466.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell241_232" position={[-0.922, 0.289, -0.765]}>
                <mesh name="Object_468" geometry={nodes.Object_468.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell242_233" position={[-0.713, 0.135, -0.605]}>
                <mesh name="Object_470" geometry={nodes.Object_470.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell243_234" position={[-0.892, 0.267, -0.879]}>
                <mesh name="Object_472" geometry={nodes.Object_472.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell244_235" position={[-0.664, 0.832, -0.902]}>
                <mesh name="Object_474" geometry={nodes.Object_474.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell245_236" position={[-0.646, 0.637, -0.654]}>
                <mesh name="Object_476" geometry={nodes.Object_476.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell246_237" position={[-0.677, 0.834, -0.641]}>
                <mesh name="Object_478" geometry={nodes.Object_478.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell247_238" position={[-0.887, 0.879, -0.603]}>
                <mesh name="Object_480" geometry={nodes.Object_480.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell248_239" position={[-0.839, 0.664, -0.881]}>
                <mesh name="Object_482" geometry={nodes.Object_482.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell249_240" position={[-0.891, 0.884, -0.813]}>
                <mesh name="Object_484" geometry={nodes.Object_484.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell250_241" position={[-0.886, 0.657, -0.666]}>
                <mesh name="Object_486" geometry={nodes.Object_486.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube_cell013_cell251_242" position={[-0.606, 0.588, -0.9]}>
                <mesh name="Object_488" geometry={nodes.Object_488.geometry} material={materials['Material.001']} />
              </group>
              <group name="Plane_243">
                <mesh name="Object_490" geometry={nodes.Object_490.geometry} material={materials.material_0} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/3dmodels/new_cube/cube3.gltf')
