/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\cube.gltf 
Author: lildrstrange11 (https://sketchfab.com/lildrstrange11)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/kevin-the-cube-9786cbc1a5dc4a8ba5361813c1283bb3
Title: Kevin The Cube
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/3dmodels/cube.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Material} rotation={[Math.PI / 2, 0, 0]} scale={1.35}/>
    </group>
  )
}

useGLTF.preload('/3dmodels/cube.gltf')
