/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 robot.gltf 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/3dmodels/robot/robot.gltf')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="robotfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <group name="hero_controler_00" position={[0, 5.215, 0]} rotation={[-1.685, 0, -1.745]}>
                    <group name="hero_controler_dupa_01" rotation={[-Math.PI / 2, 0, -1.571]}>
                      <primitive object={nodes.hero_controler_Spine_02} />
                    </group>
                    <group name="hero_controler_Footsteps" position={[-2.306, -0.407, -20.45]} rotation={[-0.02, 0.112, 1.746]} />
                  </group>
                  <group name="Object_5" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="hero" rotation={[-Math.PI / 2, 0, 0]} />
                </group>
              </group>
            </group>
          </group>
          <skinnedMesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.hero_texture} skeleton={nodes.Object_6.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/3dmodels/robot/robot.gltf')
